import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";

import { CookiesProvider } from 'next-client-cookies/server'

import { ThemeProvider } from "@/providers/theme-provider";
import { ToastProvider } from '@/providers/toast-provider'
import { ModalProvider } from '@/providers/modal-provider'

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >

          <ToastProvider />
          <ModalProvider />
          <CookiesProvider>
            {children}
          </CookiesProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
